### ISSUE TITLE
API stopped working

### ISSUE THREAD

**Issue by ikerf2001** [lmuller18/PUBGViewer#23]
The api stopped working, whats the issue with it?

**Comment by lmuller18** [comment]
I will look into this. Before I start looking, are there any other details you can provide? How did you realize that the API had stopped working?

**Comment by lmuller18** [comment]
This is from the official PUBG API:

> I just wanted to give everyone a friendly reminder that version 8.0.0 is still planned for November 30th:
> 
> https://documentation.playbattlegrounds.com/en/changelog/changelog.html#upcoming-changes
> Removed:
> 
> - The /players endpoint can no longer be queried by platform-region.
> 
> 
> Old URL:
> https://api.pubg.com/shards/{pc or xbox}-{region}/players/..
> 
> New URL:
> https://api.pubg.com/shards/{steam or xbox or kakao}/players/..

I will need to go back and correct this

**Comment by lmuller18** [comment]
Thank you for pointing this out! If you have any other comments on it I have opened an issue on my API project here: https://github.com/lmuller18/PUBGAPI/issues/2
